# TASK level variables
- name: variables from PLAY level
  hosts: localhost 
  vars: 
    Course: "Devops"
    Trainer: "Siva"
    Duration: "110Hrs"
  tasks:
  - name: check variables
    vars: 
      Course: "Devops with aws"
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Course}}, trainer {{Trainer}}, duration is {{Duration}}"
