- name: variables from PLAY level
  hosts: localhost 
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, i am learning {{Course}}, trainer {{Trainer}}, duration is {{Duration}}"
