- name: variables from PLAY level
  hosts: localhost 
  vars_files:
  - variables.yaml
  # vars_prompt:
  # - name: PERSON
  #   prompt: Please enter your person 
  #   private: false # user can see what they are entering 
  # - name: WISHES
  #   prompt: Please enter your wishes 
  #   private: false # user cann't see what they are entering 
  vars: 
    PERSON: "siva from PLAY"
    WISHES: "morning from PLAY"
  tasks:
  - name: check variables
    #vars:
     # PERSON: "siva from TASK"
      #WISHES: "morning from TASK"
    ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{WISHES}}"


#1. Command line 
#2. task 
#3. file 
#4. prompt      
      
